
  
name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - run: py -m setup build
      
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: python3 -m setup build
